name: Run Jupyter Notebook

on:
  schedule:
    - cron: '0 8 * * 1' # Runs every hour
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9' # Or your desired Python version

      - name: Install dependencies
        run: pip install -r.github/workflows/requirements.txt

      - name: Authenticate with Google Cloud OAuth2 credentials
        run: |
          # Install the necessary libraries
          pip install google-auth google-auth-oauthlib google-auth-httplib2

          # Save the credentials to a temporary file
          echo "${{ secrets.GCP_CREDENTIALS_JSON }}" > /tmp/gcp-credentials.json

          # Set GOOGLE_APPLICATION_CREDENTIALS environment variable to point to the saved credentials file
          export GOOGLE_APPLICATION_CREDENTIALS="/tmp/gcp-credentials.json"

          # Optionally, ensure this environment variable is available in future steps
          echo "GOOGLE_APPLICATION_CREDENTIALS=/tmp/gcp-credentials.json" >> $GITHUB_ENV

      - name: Run Jupyter notebook
        run: |
          # Install jupyter if not installed
          pip install jupyter
          
          # Run your notebook
          jupyter nbconvert --to notebook --execute team/Shazeb/Holdout_group/holdout_pipeline.ipynb
