name: Run Jupyter Notebook

on:
  schedule:
    - cron: '0 8 * * 1' # Runs every hour
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9' # Or your desired Python version

      - name: Install dependencies
        run: pip install -r.github/workflows/requirements.txt

      - name: Authenticate with Google Cloud
        run: |
          echo "${{ secrets.GCP_CREDENTIALS }}" > /tmp/gcp-key.json
          export GOOGLE_APPLICATION_CREDENTIALS="/tmp/gcp-key.json"
          echo "GOOGLE_APPLICATION_CREDENTIALS is set to: $GOOGLE_APPLICATION_CREDENTIALS"

      - name: Install Google Cloud Libraries
        run: |
          pip install google-cloud-storage google-cloud-bigquery google-auth

      - name: Execute notebook
        run: papermill team/Shazeb/Holdout_group/holdout_pipeline.ipynb /dev/null # Adjusted path
